# Generated by cpputils-cmake.
include /home/guajar/Desktop/programacao/cpp/cmake/build/CMakeFiles/cm.dir/flags.make
.PHONY: check-syntax
check-syntax:
	${CXX} -o /dev/null ${CXX_FLAGS} ${CXX_DEFINES} ${CXX_INCLUDES} -I/usr/include -DNDEBUG -I/usr/local/include -S ${CHK_SOURCES}